name: Handle Form Submissions

on:
  issues:
    types: [opened]

jobs:
  parse-submission:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Parse Issue and Update JSON
        run: node .github/scripts/parse-issue.js
        env:
          ISSUE_TITLE: ${{ github.event.issue.title }}
          ISSUE_BODY: ${{ github.event.issue.body }}

      - name: Commit and Push using GitHub Script
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GH_TOKEN }}
          script: |
            const { execSync } = require('child_process');
            execSync('git config user.name "github-actions"', { stdio: 'inherit' });
            execSync('git config user.email "actions@github.com"', { stdio: 'inherit' });
            execSync('git add src/data/*.json', { stdio: 'inherit' });
            try {
              execSync('git commit -m "Add entry from GitHub Issue"', { stdio: 'inherit' });
              execSync('git push origin main', { stdio: 'inherit' });
            } catch (err) {
              console.log("No changes to commit or push failed:", err.message);
            }
