name: Handle Form Submissions (API-based)

on:
  issues:
    types: [opened]

jobs:
  append-to-json:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Parse Issue and Append to Correct JSON via GitHub API
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.PAT }}
          script: |
            const title = process.env.ISSUE_TITLE;
            const body = process.env.ISSUE_BODY;

            const typeMatch = title.match(/^\[(.*?)\]/);
            if (!typeMatch) {
              console.log("⚠️ No type detected from issue title.");
              return;
            }

            const type = typeMatch[1].toLowerCase();
            const validTypes = ['paper', 'project', 'person', 'course'];
            if (!validTypes.includes(type)) {
              console.log(`⏭️ Type [${type}] not supported.`);
              return;
            }

            const jsonMatch = body.match(/```json\n([\s\S]*?)\n```/);
            if (!jsonMatch) {
              throw new Error("❌ JSON block not found in issue body.");
            }

            const newEntry = JSON.parse(jsonMatch[1]);

            const path = `src/data/${type}s.json`;
            const branch = "main";

            const { data: file } = await github.rest.repos.getContent({
              owner: context.repo.owner,
              repo: context.repo.repo,
              path,
              ref: branch
            });

            const content = Buffer.from(file.content, 'base64').toString();
            const json = JSON.parse(content);
            json.push(newEntry);

            const updatedContent = Buffer.from(JSON.stringify(json, null, 2)).toString("base64");

            await github.rest.repos.createOrUpdateFileContents({
              owner: context.repo.owner,
              repo: context.repo.repo,
              path,
              message: `Append new ${type} from GitHub Issue`,
              content: updatedContent,
              sha: file.sha,
              branch
            });

        env:
          ISSUE_TITLE: ${{ github.event.issue.title }}
          ISSUE_BODY: ${{ github.event.issue.body }}
