name: Handle Form Submissions

on:
  issues:
    types: [opened]

jobs:
  parse-submission:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Parse Issue and Update JSON
        run: node .github/scripts/parse-issue.js
        env:
          ISSUE_TITLE: ${{ github.event.issue.title }}
          ISSUE_BODY: ${{ github.event.issue.body }}

      - name: Commit and Push Changes using PAT
        env:
          PAT: ${{ secrets.PAT }}
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git remote set-url origin https://x-access-token:$PAT@github.com/vipavlovic/seqamlab.git
          git add src/data/*.json
          git commit -m "Add entry from GitHub Issue" || echo "No changes to commit"
          git push origin main
