name: Append to JSON via API

on:
  issues:
    types: [opened]

jobs:
  update-json:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Fetch and Append JSON via GitHub API
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.PAT }}
          script: |
            const path = 'src/data/papers.json';
            const branch = 'main';

            const title = process.env.ISSUE_TITLE || '';
            const body = process.env.ISSUE_BODY || '';

            const typeMatch = title.match(/^\[(.*?)\]/);
            if (!typeMatch || typeMatch[1].toLowerCase() !== 'paper') {
              console.log('⏭️ Skipping non-paper issue');
              return;
            }

            const jsonMatch = body.match(/```json\n([\s\S]*?)\n```/);
            if (!jsonMatch) throw new Error('Could not extract JSON block.');

            const newEntry = JSON.parse(jsonMatch[1]);

            const { data: file } = await github.rest.repos.getContent({
              owner: context.repo.owner,
              repo: context.repo.repo,
              path,
              ref: branch
            });

            const content = Buffer.from(file.content, 'base64').toString();
            const json = JSON.parse(content);
            json.push(newEntry);

            const updatedContent = Buffer.from(JSON.stringify(json, null, 2)).toString('base64');

            await github.rest.repos.createOrUpdateFileContents({
              owner: context.repo.owner,
              repo: context.repo.repo,
              path,
              message: 'Append new paper entry from GitHub Issue',
              content: updatedContent,
              sha: file.sha,
              branch
            });

        env:
          ISSUE_TITLE: ${{ github.event.issue.title }}
          ISSUE_BODY: ${{ github.event.issue.body }}
